# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('w1', 'W1'), ('w2', 'W2'), ('w3', 'W3'), ('w4', 'W4 Elektroniki')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
