# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0004_auto_20170305_0938'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testID', models.IntegerField()),
                ('test', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.TestModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.IntegerField()),
                ('replies', models.IntegerField(default=3)),
                ('learning_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.LearningSession')),
            ],
        ),
    ]
