# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20170305_0938'),
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningsession',
            name='testID',
        ),
        migrations.RemoveField(
            model_name='learningsession',
            name='test',
        ),
        migrations.AddField(
            model_name='learningsession',
            name='test',
            field=models.ManyToManyField(to='tests.TestModel'),
        ),
    ]
