# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20170305_0938'),
        ('learn', '0002_auto_20170306_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningsession',
            name='test',
        ),
        migrations.AddField(
            model_name='learningsession',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.TestModel'),
        ),
    ]
