# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-09 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_remove_learningsession_wrong_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningsession',
            name='correct_answers',
        ),
    ]
