# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20170305_0938'),
        ('learn', '0003_auto_20170306_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionstatus',
            name='questionID',
        ),
        migrations.AddField(
            model_name='questionstatus',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.TestModel'),
        ),
    ]
