# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20170306_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningsession',
            old_name='ended',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 6, 16, 6, 6, 252757, tzinfo=utc)),
        ),
    ]
