# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20170306_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionStatus',
            new_name='QuestionStatistic',
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='learningsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionstatistic',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.QuestionModel'),
        ),
    ]
