# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20170306_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstatistic',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
