# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-07 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_questionstatistic_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
    ]
