# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0002_auto_20170320_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMarkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='mark',
            field=models.ManyToManyField(blank=True, related_name='testmark', to='tests.TestMarkModel'),
        ),
    ]
