# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testmodel_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
