# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 08:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20170320_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmarkmodel',
            name='mark',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
