# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20170305_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='question',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
