# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20170320_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='mark',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='mark',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='testmark', to='tests.TestMarkModel'),
            preserve_default=False,
        ),
    ]
