# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20170320_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmarkmodel',
            name='test',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='testmark', to='tests.TestModel'),
        ),
    ]
