# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-09 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20170320_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.QuestionModel'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.TestModel'),
        ),
    ]
