# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20170409_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='department',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='teacher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
